# Generated by Django 5.2.13 on 2026-04-28 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactonegocio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecontacto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='contactonegocio.cliente'),
        ),
        migrations.AlterField(
            model_name='clientedocumento',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documento', to='contactonegocio.cliente'),
        ),
    ]
