# Generated by Django 5.2.13 on 2026-04-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationlead_onboardingtoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='onboardingtoken',
            new_name='organizatio_purpose_83ac0f_idx',
            old_name='organizatio_purpose_274350_idx',
        ),
    ]
