# Generated by Django 5.2.13 on 2026-04-20 21:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_rename_organizatio_purpose_274350_idx_organizatio_purpose_83ac0f_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCompanyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('plan', models.CharField(default='starter_2_users', max_length=32)),
                ('status', models.CharField(choices=[('pending_payment', 'Pago pendiente'), ('authorized', 'Suscripción autorizada'), ('provisioned', 'Empresa creada'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], db_index=True, default='pending_payment', max_length=32)),
                ('preapproval_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('last_notified_payment_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de empresa pendiente',
                'verbose_name_plural': 'Registros de empresa pendientes',
                'indexes': [models.Index(fields=['email', 'status'], name='organizatio_email_2499ac_idx')],
            },
        ),
    ]
