# Generated by Django 5.2.13 on 2026-04-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_pending_company_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationlead',
            name='custom_requirements',
            field=models.TextField(blank=True, default='', help_text='Funcionalidades o alcance del sistema que solicita el cliente (plan personalizado).'),
        ),
    ]
